### PR TITLE
Updating existing site detail

### PR DESCRIPTION
**Pull request by connorjbracy**
Put in a hotfix for an issue that prevented the one sanity check this site has for validating that the website will work properly

### CODE REVIEW

**Comment by connorjbracy** [comment]
> Put in a hotfix for an issue that prevented the one sanity check this site has for validating that the website will work properly

@sbillinge, please review the comment and hotfix described in this first commit. It's definitely a bit hacky (i.e., probably shouldn't be the state of things going forward) but I'm not sure why things are done the way they are with the Spinx config not matching the project layout so that commit is my fix for now. This has been noted in Issue #35

**Comment by connorjbracy** [comment]
> Put in a hotfix for an issue that prevented the one sanity check this site has for validating that the website will work properly

@sbillinge The second commit here contains the writeup for adding to, modifying, and publishing changes to diffpy.org. It's a bit lengthy so review at your own discretion (for time sake), but it does also contain the (couple) steps you'll need to do in order to publish updates to the website (see the "Maintainers (Publishing Changes)" section of the [README.md](https://github.com/diffpy/diffpy.github.io/pull/34/commits/f860f1b88674a953603d903821201e9dfe93c568) file in the second commit within this PR)

**Comment by connorjbracy** [comment]
This last [pair](https://github.com/diffpy/diffpy.github.io/pull/34/commits/30a780a2ab8726d72860e5d661aab7557d81a8ea) of [commits](https://github.com/diffpy/diffpy.github.io/pull/34/commits/645335f83b49f2d3a57bc544f56f85591c232195) should be everything needed to update the site in its current incarnation and be prepared for the subsequent update of `pdfgetx v2.2.0` tomorrow.

**Comment by connorjbracy** [comment]
@sbillinge, this last [pair](https://github.com/diffpy/diffpy.github.io/pull/34/commits/30a780a2ab8726d72860e5d661aab7557d81a8ea) of [commits](https://github.com/diffpy/diffpy.github.io/pull/34/commits/645335f83b49f2d3a57bc544f56f85591c232195) should be everything needed to update the site in its current incarnation and be prepared for the subsequent update of `pdfgetx v2.2.0` tomorrow.

**Review by sbillinge — COMMENTED** [review]
Thanks @connorjbracy 


1.  The first commit (update make so that link testing works) looks fine, and well documented.
2.  commit 2 (changes to the docs) is too difficult to review in a PR.  I suggest merging it and having me/others proof read everything then.....
2. There are 55 updated files in this PR and most seem to be somehow associated with a particular release.  Things like `static_root/doc/pdfgetx/2.1.1/_sources/files.rst.txt` which look to me as if they may not need to to be in the PR.  Please can you check/confirm?

**Comment by connorjbracy** [comment]
> 1. The first commit (update make so that link testing works) looks fine, and well documented.

Sounds good

> 2. commit 2 (changes to the docs) is too difficult to review in a PR.  I suggest merging it and having me/others proof read everything then.....

Agreed

> 3. There are 55 updated files in this PR and most seem to be somehow associated with a particular release.  Things like `static_root/doc/pdfgetx/2.1.1/_sources/files.rst.txt` which look to me as if they may not need to to be in the PR.  Please can you check/confirm?

That is correct. The files are the documents/supporting contents of the `pdfgetx v2.1.1` that Tim made some months ago but never got published on the website. That is, `pdfgetx v2.1.1` exists on CTV already, but is not mentioned on the website (this pair of commits fixes this discrepancy). 

@sbillinge, let me know if you want me to revert the (3) commits from the PR and move them to a separate PR (I decided to lump all these into one PR as they all bring the website into the state that it currently should be and figured it would eliminate any need for possible merge resolution if they were split into multiple PR's - i.e., less work for you)

**Pull request merged**
