### PR TITLE
DOC/WIP: add to diffpy website

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@CJ-Wright, @chiahaoliu  - this seems at a very early WIP stage.  Please test in a `gh-pages` branch of your forked repos.  These get published at `http://USER.github.io/diffpy.github.io`.

Here is how to setup the repo so that compiled webpage publishes to your `gh-pages`:

One time setup

```sh
git clone -b source https://github.com/diffpy/diffpy.github.io.git
cd diffpy.github.io
git remote add cj https://github.com/CJ-Wright/diffpy.github.io.git
# 'origin/master' is the current diffpy.org
# your version will publish via 'gh-pages' branch
git branch gh-pages origin/master
git push -u cj gh-pages:gh-pages
```

Create `GNUmakefile` file with the following content:

```make
include Makefile
PUBLISHBRANCH = gh-pages
```

Work on the `mappdf` branch and publish it to gh-pages:
```sh
make html
make publish-prepare
## optional - review changes to be published
# git show --word-diff gh-pages
make publish-push
```

**Comment by CJ-Wright** [comment]
I am just running a local http server and making the build. That way I can look at the pages locally. Is there a problem with this PR specifically? I know it's not ready to go in yet but I didn't think it was harming anything, right?

**Comment by pavoljuhas** [comment]
Local web server is a good trick.  The PR does not harm anything, but is a bit confusing.  I usually submit PR-s when ready to go, before then I keep the work non-advertised.

**Comment by CJ-Wright** [comment]
I usually like to put things up as early as possible so that others can comment on the general direction before I sink too much work into something that no one wants.

**Comment by pavoljuhas** [comment]
So is it decided if mappdf needs a page at diffpy.org or not?  cc: @sbillinge

It may be better to discuss what to do and what not at the bg-dev mailing list.  From my POV this looked like something you really wanted to merge.

BTW, the mappdf package does not seem ready - no setup.py, no README, and a few other issues I commented on today.  Please, have the package ready before making a PR to add it to diffpy.org.

**Comment by sbillinge** [comment]
Yes, we want to link to it from diffpy.org so it needs to be to similar
standards. Naming consistently makes sense to me (so diffpy.mapPDF).

**Comment by pavoljuhas** [comment]
Closing - this PR is not even started.  I understand PRs as what their name states - a request to pull.  I'd be glad to help with an early work, but PR with no description is not a way to do so.  Please post an email to bg-dev or create an issue and describe what you are trying to do and what the questions are (if applicable, include a URL to your WIP branch).

**Comment by pavoljuhas** [comment]
> Naming consistently makes sense to me (so diffpy.mapPDF).

I'd suggest to use lowercase `diffpy.mappdf`.  Python PEP 8 recommends lowercase module and package names.  It is better if repository and package names were the same.

**Pull request closed without merging**
